# Generated by Django 4.2.7 on 2023-12-01 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_record',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_fname', models.CharField(max_length=100)),
                ('emp_lname', models.CharField(max_length=100)),
                ('emp_email', models.CharField(max_length=100)),
                ('emp_phone', models.IntegerField()),
                ('emp_address', models.CharField(max_length=250)),
                ('emp_designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='timing_table',
            fields=[
                ('timing_table_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('punch_in', models.DateTimeField(blank=True, null=True)),
                ('punch_out', models.DateTimeField(blank=True, null=True)),
                ('break_start', models.DateTimeField(blank=True, null=True)),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('working_day', models.DateTimeField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employee_record')),
            ],
        ),
        migrations.CreateModel(
            name='time_off_table',
            fields=[
                ('Timeoff_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('timeoff_available', models.TextField()),
                ('emp_fname', models.CharField(max_length=100)),
                ('emp_lname', models.CharField(max_length=100)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employee_record')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_table',
            fields=[
                ('schedule_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('assigned_schedule', models.DateTimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emp_fname', models.CharField(max_length=100)),
                ('emp_lname', models.CharField(max_length=100)),
                ('emp_designation', models.CharField(max_length=100, null=True)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.employee_record')),
                ('timeoff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.time_off_table')),
            ],
        ),
        migrations.CreateModel(
            name='payroll_table',
            fields=[
                ('payroll_table_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('emp_sin', models.IntegerField()),
                ('emp_account_Number', models.BigIntegerField()),
                ('emp_payrate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pay_cycle', models.SmallIntegerField(default=1)),
                ('fk_emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.employee_record')),
                ('fk_schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.schedule_table')),
            ],
        ),
    ]
