# Generated by Django 4.2.7 on 2023-12-05 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_table',
            name='fk_schedule_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.schedule_table'),
        ),
        migrations.AlterField(
            model_name='schedule_table',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.employee_record'),
        ),
        migrations.AlterField(
            model_name='schedule_table',
            name='timeoff_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.time_off_table'),
        ),
        migrations.AlterField(
            model_name='time_off_table',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.employee_record'),
        ),
        migrations.AlterField(
            model_name='timing_table',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.employee_record'),
        ),
    ]
