# Generated by Django 4.2.7 on 2023-12-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_payroll_table_fk_schedule_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll_table',
            name='payroll_table_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='schedule_table',
            name='schedule_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='time_off_table',
            name='Timeoff_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timing_table',
            name='timing_table_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
