# Generated by Django 4.2.7 on 2023-12-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_payroll_table_payroll_table_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
