# Generated by Django 4.2.7 on 2023-12-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_datetimerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateTimeRecord',
        ),
        migrations.AlterField(
            model_name='timing_table',
            name='break_end',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing_table',
            name='break_start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing_table',
            name='punch_in',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing_table',
            name='punch_out',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
