# Generated by Django 4.2.7 on 2023-12-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_timing_table_working_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing_table',
            name='break_end',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing_table',
            name='break_start',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing_table',
            name='punch_in',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing_table',
            name='punch_out',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='timing_table',
            name='working_day',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
