version: '3'

services:
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeedb
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mysql_data_5:/var/lib/mysql

  node-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
    command: ["wait-for-it", "--", "npm", "start"] 
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=employeedb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data_5:

